# Path: docker-compose.yml

version: '3.8'

networks:
  cv_network:
    driver: bridge

volumes:
  web_node_modules:
  api_node_modules:
  test_api_node_modules:

services:
  web:
    container_name: cv_web
    build: web
    image: web
    networks:
      - cv_network
    volumes:
      - ./web/:/web
      - web_node_modules:/web/node_modules
    ports:
      - 3000:3000
    env_file:
      - project.env

  api:
    container_name: cv_api
    build: api
    image: api
    networks:
      - cv_network
    volumes:
      - ./api/:/api
      - api_node_modules:/api/node_modules
    ports:
      - 8000:8000

  test_api:
    container_name: cv_test_api
    build:
      context: ./api
      dockerfile: Dockerfile.test
    image: test_api
    networks:
      - cv_network
    volumes:
      - ./api/:/api
      - test_api_node_modules:/api/node_modules
    env_file:
      - project.env
    depends_on:
      - api

  nginx:
    container_name: cv_nginx
    image: nginx:1.25.2-alpine-slim
    networks:
      - cv_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api
    ports:
      - 7800:7800
