version: '3.8'

volumes:
  astro_node_modules:

services:
  web:
    container_name: cv_web
    build: web
    image: web
    restart: "no"
    volumes:
      - ./web/:/app
      - astro_node_modules:/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - project.env

  nginx:
    container_name: cv_nginx
    image: nginx:1.25.2-alpine-slim
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - 7800:7800
