# Path: docker-compose.yml

version: '3.8'

networks:
  cv_network:
    driver: bridge

volumes:
  web_node_modules:
  api_node_modules:

services:
  web:
    container_name: cv_web
    build: web
    image: web
    restart: "no"
    networks:
      - cv_network
    volumes:
      - ./web/:/app
      - web_node_modules:/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - project.env

  api:
    container_name: cv_api
    build: api
    image: api
    restart: "no"
    networks:
      - cv_network
    volumes:
      - ./api/:/app
      - api_node_modules:/app/node_modules
    ports:
      - 8000:8000

  nginx:
    container_name: cv_nginx
    image: nginx:1.25.2-alpine-slim
    networks:
      - cv_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api
    ports:
      - 7800:7800
