# Path: docker-compose.yml

version: '3.8'

networks:
  cv_network:
    driver: bridge

volumes:
  web_node_modules:
  api_node_modules:
  test_api_node_modules:
  db_nosql_data:
  test_db_nosql_data:

services:
  web:
    container_name: cv_web
    build: web
    image: web
    networks:
      - cv_network
    volumes:
      - ./web/:/web
      - web_node_modules:/web/node_modules
    ports:
      - 3000:3000
    env_file:
      - project.env

  api:
    container_name: cv_api
    build: api
    image: api
    networks:
      - cv_network
    volumes:
      - ./api/:/api
      - api_node_modules:/api/node_modules
    ports:
      - 8000:8000

  test_api:
    container_name: cv_test_api
    build:
      context: ./api
      dockerfile: Dockerfile.test
    image: test_api
    networks:
      - cv_network
    volumes:
      - ./api/:/api
      - test_api_node_modules:/api/node_modules
    env_file:
      - project.test.env
    depends_on:
      - api

  test_watch_api:
    container_name: cv_test_watch_api
    build:
      context: ./api
      dockerfile: Dockerfile.test_watch
    image: test_watch_api
    networks:
      - cv_network
    volumes:
      - ./api/:/api
      - test_api_node_modules:/api/node_modules
    env_file:
      - project.test.env
    depends_on:
      - test_api

  nginx:
    container_name: cv_nginx
    image: nginx:1.25.2-alpine-slim
    networks:
      - cv_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api
    ports:
      - 7800:7800

  db_nosql_data:
    image: mongo:7.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=yourpassword
    volumes:
      - db_nosql_data:/data/db
    networks:
      - cv_network
    ports:
      - 27017:27017

  test_db_nosql_data:
    image: mongo:7.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=yourpassword
    volumes:
      - test_db_nosql_data:/data/db
    networks:
      - cv_network
    ports:
      - 27018:27017
