version: "3.4"

volumes:
  astro_node_modules:

services:
  ui:
    container_name: cv_ui
    build: ui
    image: ui
    restart: "no"
    volumes:
      - ./ui/:/app
      - astro_node_modules:/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - project.env

  nginx:
    container_name: cv_nginx
    image: nginx:1.25.2-alpine-slim
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ui
    ports:
      - 7800:7800
