
# Path: api/Dockerfile.test_watch

FROM oven/bun:1.0.15-slim

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# # Instalar dependencias necesarias para obtener la última versión de watchexec
# RUN apt-get update && \
#     apt-get install -y curl xz-utils jq netcat && \
#     LATEST_RELEASE=$(curl -s https://api.github.com/repos/watchexec/watchexec/releases/latest | jq -r '.tag_name' | sed 's/^v//') && \
#     WATCHEXEC_URL="https://github.com/watchexec/watchexec/releases/download/v${LATEST_RELEASE}/watchexec-${LATEST_RELEASE}-x86_64-unknown-linux-gnu.tar.xz" && \
#     curl -sSL $WATCHEXEC_URL | tar -xJ && \
#     mv watchexec-${LATEST_RELEASE}-x86_64-unknown-linux-gnu/watchexec /usr/local/bin/ && \
#     chmod +x /usr/local/bin/watchexec

# Instalar dependencias necesarias y descargar watchexec
RUN apt-get update && \
    apt-get install -y curl xz-utils netcat && \
    curl -L "https://github.com/watchexec/watchexec/releases/download/cli-v1.20.0/watchexec-1.20.0-x86_64-unknown-linux-gnu.tar.xz" | tar xJ && \
    mv watchexec-1.20.0-x86_64-unknown-linux-gnu/watchexec /usr/local/bin/ && \
    chmod +x /usr/local/bin/watchexec

# Copiar los archivos package.json y bun.lockb al contenedor
COPY package.json bun.lockb ./

# Instalar las dependencias de la aplicación
RUN bun install

# Copiar el resto de los archivos del proyecto
COPY . .

# CMD sh -c "while ! nc -z test_api 8000; do sleep 5; done; watchexec --debounce 500 --watch src --watch test --exts 'ts,json' --restart --signal HUP ./restart-bun-test.sh"
CMD sh -c "while ! nc -z test_api 8000; do sleep 5; done; watchexec --watch src --watch test --exts 'ts,json' -- ./restart-bun-test.sh"
