# Path: api/Dockerfile.test

FROM oven/bun:1.0.13-slim

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Instalar dependencias necesarias y descargar watchexec
RUN apt-get update && \
    apt-get install -y curl xz-utils netcat lsof && \
    curl -L "https://github.com/watchexec/watchexec/releases/download/cli-v1.20.0/watchexec-1.20.0-x86_64-unknown-linux-gnu.tar.xz" | tar xJ && \
    mv watchexec-1.20.0-x86_64-unknown-linux-gnu/watchexec /usr/local/bin/ && \
    chmod +x /usr/local/bin/watchexec

# Copiar los archivos package.json y bun.lockb al contenedor
COPY package.json bun.lockb ./

# Instalar las dependencias de la aplicación
RUN bun install

# Copiar el resto de los archivos del proyecto
COPY . .

COPY restart-bun.sh /usr/src/app/restart-bun.sh
RUN chmod +x /usr/src/app/restart-bun.sh

CMD sh -c "watchexec --watch src --watch test --exts 'ts,json' --restart --signal HUP ./restart-bun.sh"
